### ISSUE TITLE
Cache Minified Images

### ISSUE THREAD

**Issue by RehanSaeed** [milewski/imagemin-loader#6]
Repeatedly minifying an image should be avoided. A cache containing hashes of minified files should be saved to disk so it can be checked in to Git and shared across a team.

**Comment by milewski** [comment]
Okay let's discuss about this feature: 

Pretty much you want to include the output in git which currently you can totally do.. But everytime you recompile your bundle the output gets overwritten.. So it will trigger a change on git.. 

A easy way to avoid it would be if before overriding it checks if the destination file already exists... If so 'skip' the image min step.. 

But don't you think it's preferable to keep the original image source in git instead of its minified version? Let's say down the line you decide to tweak some settings on it, increase the minification params... I could avoid a re-minification on the second build by using the checking method described above.. 

Another thing I can think of is that is not a loader job to generate a hashfile but a plugin. So whether I make a plugin to generate this hash file containing hash of the destination v source to compare if it has been already minified or not..  Or I could generate a basic text file and append/check hashes on it every time a image gets minified (at the loader level)
